apiVersion: v1
kind: Service
metadata:
  name: kubernetes-mcp
  namespace: opsgentic
spec:
  selector:
    app: kubernetes-mcp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31081
  type: NodePort
