from __future__ import annotations

import base64
import urllib.parse
from typing import Optional

import httpx

from opsgentic.gitops.providers import get_provider


def create_pull_request(
    plan: dict,
    *,
    run_id: str = "unknown",
    hypothesis: str = "",
    validation_report: Optional[dict] = None,
) -> str:
    """Open a remediation-proposal PR/MR on the plan's provider. Returns the URL.

    Without a usable token for the host, returns a stub URL (side-effect free).
    """
    validation_report = validation_report or {}
    cfg = get_provider(plan.get("host", "github.com"))
    if cfg is None or not cfg.token:
        return f"stub://no-token/{plan.get('target_repo', 'unknown')}/pull/0"

    ptype = plan.get("provider") or cfg.type
    content = _proposal_markdown(plan, run_id, hypothesis, validation_report)
    path = _proposal_path(plan.get("path"), run_id)
    branch = f"opsgentic/remediation-{run_id[:8]}"
    title = f"[opsgentic] {plan.get('summary', 'remediation')}"
    body = f"Automated remediation proposal. See `{path}`.\n\nRisk: {plan.get('risk')}"
    kwargs = dict(cfg=cfg, plan=plan, branch=branch, path=path, content=content, title=title, body=body)

    if ptype == "github":
        return _github_pr(**kwargs)
    if ptype == "gitea":
        return _gitea_pr(**kwargs)
    if ptype == "gitlab":
        return _gitlab_mr(**kwargs)
    raise NotImplementedError(f"provider '{ptype}' is not supported (github | gitea | gitlab)")


def _json(resp: httpx.Response):
    resp.raise_for_status()
    return resp.json()


def _base_or_default(plan: dict, default: Optional[str]) -> Optional[str]:
    rev = (plan.get("revision") or "").strip()
    return rev if rev and rev != "HEAD" else default


def _proposal_path(path: Optional[str], run_id: str) -> str:
    p = (path or "").strip("/")
    if p.endswith((".yaml", ".yml")):
        p = p.rsplit("/", 1)[0] if "/" in p else ""
    prefix = f"{p}/" if p else ""
    return f"{prefix}remediations/{run_id}.md"


def _proposal_markdown(plan: dict, run_id: str, hypothesis: str, validation_report: dict) -> str:
    checks = "\n".join(
        f"- {'PASS' if r.get('passed') else 'FAIL'} `{r.get('name')}` — {r.get('detail')}"
        for r in (validation_report.get("results") or [])
    )
    return (
        f"# Remediation proposal\n\n"
        f"- Run: `{run_id}`\n"
        f"- Risk: **{plan.get('risk', 'unknown')}**\n"
        f"- Source: `{plan.get('source', 'unknown')}`\n"
        f"- Target: `{plan.get('path')}` in `{plan.get('target_repo')}`\n\n"
        f"## Summary\n\n{plan.get('summary', '')}\n\n"
        f"## Root cause hypothesis\n\n{hypothesis or '(none)'}\n\n"
        f"## Validation\n\n{validation_report.get('summary', '')}\n\n{checks}\n\n"
        f"## Proposed change\n\n```diff\n{plan.get('diff', '')}\n```\n\n"
        f"---\nGenerated by opsgentic. Review and apply via GitOps.\n"
    )


def _github_pr(*, cfg, plan, branch, path, content, title, body) -> str:
    owner, repo = plan["owner"], plan["repo"]
    api = cfg.api_base.rstrip("/")
    headers = {
        "Authorization": f"Bearer {cfg.token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    enc = base64.b64encode(content.encode()).decode()
    with httpx.Client(timeout=30.0, headers=headers) as c:
        base = _base_or_default(plan, None) or _json(c.get(f"{api}/repos/{owner}/{repo}"))["default_branch"]
        base_sha = _json(c.get(f"{api}/repos/{owner}/{repo}/git/ref/heads/{base}"))["object"]["sha"]

        r = c.post(f"{api}/repos/{owner}/{repo}/git/refs", json={"ref": f"refs/heads/{branch}", "sha": base_sha})
        if r.status_code not in (201, 422):
            r.raise_for_status()

        put = {"message": title, "content": enc, "branch": branch}
        r = c.put(f"{api}/repos/{owner}/{repo}/contents/{path}", json=put)
        if r.status_code == 422:
            put["sha"] = _json(c.get(f"{api}/repos/{owner}/{repo}/contents/{path}", params={"ref": branch}))["sha"]
            r = c.put(f"{api}/repos/{owner}/{repo}/contents/{path}", json=put)
        r.raise_for_status()

        pr = c.post(f"{api}/repos/{owner}/{repo}/pulls", json={"title": title, "head": branch, "base": base, "body": body})
        if pr.status_code == 422:
            items = _json(c.get(f"{api}/repos/{owner}/{repo}/pulls", params={"head": f"{owner}:{branch}", "state": "open"}))
            if items:
                return items[0]["html_url"]
        pr.raise_for_status()
        return pr.json()["html_url"]


def _gitea_pr(*, cfg, plan, branch, path, content, title, body) -> str:
    owner, repo = plan["owner"], plan["repo"]
    api = cfg.api_base.rstrip("/")
    headers = {"Authorization": f"token {cfg.token}", "Accept": "application/json"}
    enc = base64.b64encode(content.encode()).decode()
    with httpx.Client(timeout=30.0, headers=headers) as c:
        base = _base_or_default(plan, _json(c.get(f"{api}/repos/{owner}/{repo}")).get("default_branch", "main"))

        r = c.post(f"{api}/repos/{owner}/{repo}/branches", json={"new_branch_name": branch, "old_branch_name": base})
        if r.status_code not in (201, 409):
            r.raise_for_status()

        payload = {"content": enc, "message": title, "branch": branch}
        r = c.post(f"{api}/repos/{owner}/{repo}/contents/{path}", json=payload)
        if r.status_code in (409, 422):
            payload["sha"] = _json(c.get(f"{api}/repos/{owner}/{repo}/contents/{path}", params={"ref": branch}))["sha"]
            r = c.put(f"{api}/repos/{owner}/{repo}/contents/{path}", json=payload)
        r.raise_for_status()

        pr = _json(c.post(f"{api}/repos/{owner}/{repo}/pulls", json={"title": title, "head": branch, "base": base, "body": body}))
        return pr.get("html_url") or pr.get("url")


def _gitlab_mr(*, cfg, plan, branch, path, content, title, body) -> str:
    api = cfg.api_base.rstrip("/")
    pid = urllib.parse.quote(plan["slug"], safe="")
    headers = {"PRIVATE-TOKEN": cfg.token}
    with httpx.Client(timeout=30.0, headers=headers) as c:
        base = _base_or_default(plan, _json(c.get(f"{api}/projects/{pid}")).get("default_branch", "main"))

        r = c.post(f"{api}/projects/{pid}/repository/branches", params={"branch": branch, "ref": base})
        if r.status_code not in (201, 400):   # 400: branch already exists
            r.raise_for_status()

        commit = {
            "branch": branch,
            "commit_message": title,
            "actions": [{"action": "create", "file_path": path, "content": content}],
        }
        r = c.post(f"{api}/projects/{pid}/repository/commits", json=commit)
        if r.status_code == 400:              # file exists -> update
            commit["actions"][0]["action"] = "update"
            r = c.post(f"{api}/projects/{pid}/repository/commits", json=commit)
        r.raise_for_status()

        mr = _json(c.post(
            f"{api}/projects/{pid}/merge_requests",
            json={"source_branch": branch, "target_branch": base, "title": title, "description": body},
        ))
        return mr["web_url"]
